/**
 * Correspondance des ENUMs PostgreSQL pour JavaScript
 */

// Rôles des comptes
const COMPTE_ROLE = {
  ADMINISTRATEUR_PLATEFORME: 'ADMINISTRATEUR_PLATEFORME',
  BLOGUEUR_PLATEFORME: 'BLOGUEUR_PLATEFORME',
  STAFF_PLATEFORME: 'STAFF_PLATEFORME',
  ADMINISTRATEUR_COMPAGNIE: 'ADMINISTRATEUR_COMPAGNIE',
  STAFF_COMPAGNIE: 'STAFF_COMPAGNIE',
  BLOGUEUR_COMPAGNIE: 'BLOGUEUR_COMPAGNIE',
  ADMINISTRATEUR_EMBRANCHEMENT_COMPAGNIE: 'ADMINISTRATEUR_EMBRANCHEMENT_COMPAGNIE',
  STAFF_EMBRANCHEMENT_COMPAGNIE: 'STAFF_EMBRANCHEMENT_COMPAGNIE',
  BLOGUEUR_EMBRANCHEMENT_COMPAGNIE: 'BLOGUEUR_EMBRANCHEMENT_COMPAGNIE',
  ADMINISTRATEUR_RESTAURANT_FAST_FOOD: 'ADMINISTRATEUR_RESTAURANT_FAST_FOOD',
  STAFF_RESTAURANT_FAST_FOOD: 'STAFF_RESTAURANT_FAST_FOOD',
  BLOGUEUR_RESTAURANT_FAST_FOOD: 'BLOGUEUR_RESTAURANT_FAST_FOOD',
  UTILISATEUR_PRIVE_SIMPLE: 'UTILISATEUR_PRIVE_SIMPLE',
  UTILISATEUR_VENDEUR: 'UTILISATEUR_VENDEUR'
};

// Statuts des comptes
const STATUT_COMPTE = {
  EST_AUTHENTIFIE: 'EST_AUTHENTIFIE',
  NON_AUTHENTIFIE: 'NON_AUTHENTIFIE',
  SUSPENDU: 'SUSPENDU',
  BANNI: 'BANNI'
};

// Types de promotions
const TYPES_PROMO = {
  POURCENTAGE: 'POURCENTAGE',
  MONTANT_FIXE: 'MONTANT_FIXE',
  DEUX_POUR_UN: 'DEUX_POUR_UN',
  LIVRAISON_GRATUITE: 'LIVRAISON_GRATUITE',
  MENU_OFFERT: 'MENU_OFFERT',
  CODE_PROMO: 'CODE_PROMO',
  FIDELITE: 'FIDELITE'
};

// Statuts de commande
const STATUT_COMMANDE = {
  EN_ATTENTE: 'EN_ATTENTE',
  CONFIRMEE: 'CONFIRMEE',
  EN_PREPARATION: 'EN_PREPARATION',
  PRETE: 'PRETE',
  EN_LIVRAISON: 'EN_LIVRAISON',
  LIVREE: 'LIVREE',
  RECUPEREE: 'RECUPEREE',
  ANNULEE: 'ANNULEE',
  REMBOURSEE: 'REMBOURSEE'
};

// Types d'entités de référence
const ENTITE_REFERENCE = {
  PLATEFORME: 'PLATEFORME',
  COMPAGNIE_TRANSPORT: 'COMPAGNIE_TRANSPORT',
  EMPLACEMENT_TRANSPORT: 'EMPLACEMENT_TRANSPORT',
  RESTAURANT_FAST_FOOD: 'RESTAURANT_FAST_FOOD',
  EMPLACEMENT_RESTAURANT: 'EMPLACEMENT_RESTAURANT',
  BOUTIQUE: 'BOUTIQUE',
  PRODUIT_BOUTIQUE: 'PRODUIT_BOUTIQUE',
  MENU: 'MENU',
  COMPTE: 'COMPTE',
  LIVREUR: 'LIVREUR',
  SERVICE_TRANSPORT: 'SERVICE_TRANSPORT'
};

// Statuts d'avis
const STATUT_AVIS = {
  EN_ATTENTE: 'EN_ATTENTE',
  PUBLIE: 'PUBLIE',
  REJETE: 'REJETE',
  SIGNALE: 'SIGNALE',
  MASQUE: 'MASQUE'
};

// Canaux de notification
const CANAL_NOTIFICATION = {
  IN_APP: 'IN_APP',
  PUSH_MOBILE: 'PUSH_MOBILE',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  WHATSAPP: 'WHATSAPP'
};

// Priorités de notification
const PRIORITE_NOTIFICATION = {
  BASSE: 'BASSE',
  NORMALE: 'NORMALE',
  HAUTE: 'HAUTE',
  CRITIQUE: 'CRITIQUE'
};

// Types de documents
const TYPE_DOCUMENT = {
  CNI_RECTO: 'CNI_RECTO',
  CNI_VERSO: 'CNI_VERSO',
  PASSEPORT: 'PASSEPORT',
  PERMIS_CONDUIRE: 'PERMIS_CONDUIRE',
  JUSTIFICATIF_DOMICILE: 'JUSTIFICATIF_DOMICILE',
  EXTRAIT_NAISSANCE: 'EXTRAIT_NAISSANCE',
  REGISTRE_COMMERCE: 'REGISTRE_COMMERCE',
  ATTESTATION_FISCALE: 'ATTESTATION_FISCALE',
  CONTRAT: 'CONTRAT',
  BON_COMMANDE: 'BON_COMMANDE',
  FACTURE: 'FACTURE',
  RECU_PAIEMENT: 'RECU_PAIEMENT',
  PHOTO_LIVREUR: 'PHOTO_LIVREUR',
  AUTRE: 'AUTRE'
};

// Statuts de document
const STATUT_DOCUMENT = {
  EN_ATTENTE_VALIDATION: 'EN_ATTENTE_VALIDATION',
  VALIDE: 'VALIDE',
  REFUSE: 'REFUSE',
  EXPIRE: 'EXPIRE',
  REMPLACE: 'REMPLACE'
};

// Types de mouvements de points
const TYPE_MOUVEMENT_POINTS = {
  GAIN_ACHAT: 'GAIN_ACHAT',
  GAIN_PARRAINAGE: 'GAIN_PARRAINAGE',
  GAIN_BONUS: 'GAIN_BONUS',
  UTILISATION: 'UTILISATION',
  EXPIRATION: 'EXPIRATION',
  CORRECTION_MANUELLE: 'CORRECTION_MANUELLE',
  TRANSFERT: 'TRANSFERT'
};

// Catégories d'articles de blog
const CATEGORIES_ARTICLE = {
  ACTUALITE: 'ACTUALITE',
  TUTORIEL: 'TUTORIEL',
  ASTUCE: 'ASTUCE',
  GUIDE: 'GUIDE',
  AVIS: 'AVIS',
  TEST_PRODUIT: 'TEST_PRODUIT',
  COMPARAISON: 'COMPARAISON',
  PROMOTION: 'PROMOTION',
  EVENEMENT: 'EVENEMENT',
  INTERVIEW: 'INTERVIEW',
  DOSSIER: 'DOSSIER',
  OPINION: 'OPINION',
  TENDANCE: 'TENDANCE',
  VIE_LOCALE: 'VIE_LOCALE',
  TRANSPORT: 'TRANSPORT',
  RESTAURATION: 'RESTAURATION',
  BOUTIQUE: 'BOUTIQUE',
  COMMUNAUTE: 'COMMUNAUTE'
};

// Types de conversations
const TYPE_CONVERSATION = {
  DIRECT: 'DIRECT',
  GROUPE: 'GROUPE',
  SUPPORT: 'SUPPORT',
  COMMANDE: 'COMMANDE',
  LIVRAISON: 'LIVRAISON',
  SERVICE_CLIENT: 'SERVICE_CLIENT',
  NOTIFICATION_ADMIN: 'NOTIFICATION_ADMIN',
  ANNONCE_PLATEFORME: 'ANNONCE_PLATEFORME',
  SIGNALEMENT: 'SIGNALEMENT',
  RECLAMATION: 'RECLAMATION'
};

// Rôles dans une conversation
const ROLE_CONVERSATION = {
  ADMIN: 'ADMIN',
  MODERATEUR: 'MODERATEUR',
  PARTICIPANT: 'PARTICIPANT',
  OBSERVATEUR: 'OBSERVATEUR',
  INVITE: 'INVITE'
};

module.exports = {
  COMPTE_ROLE,
  STATUT_COMPTE,
  TYPES_PROMO,
  STATUT_COMMANDE,
  ENTITE_REFERENCE,
  STATUT_AVIS,
  CANAL_NOTIFICATION,
  PRIORITE_NOTIFICATION,
  TYPE_DOCUMENT,
  STATUT_DOCUMENT,
  TYPE_MOUVEMENT_POINTS,
  CATEGORIES_ARTICLE,
  TYPE_CONVERSATION,
  ROLE_CONVERSATION
};