// src/utils/constants/errorCodes.js
// Codes d'erreur standardisés pour l'API

module.exports = {
  // Authentification
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED:        'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID:        'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING:        'AUTH_TOKEN_MISSING',
  AUTH_ACCOUNT_SUSPENDED:    'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_BANNED:       'AUTH_ACCOUNT_BANNED',
  AUTH_CODE_INVALID:         'AUTH_CODE_INVALID',
  AUTH_CODE_EXPIRED:         'AUTH_CODE_EXPIRED',
  AUTH_EMAIL_NOT_VERIFIED:   'AUTH_EMAIL_NOT_VERIFIED',

  // Ressources
  NOT_FOUND:                 'NOT_FOUND',
  ALREADY_EXISTS:            'ALREADY_EXISTS',
  CONFLICT:                  'CONFLICT',

  // Validation
  VALIDATION_ERROR:          'VALIDATION_ERROR',
  INVALID_INPUT:             'INVALID_INPUT',
  MISSING_FIELD:             'MISSING_FIELD',

  // Autorisation
  FORBIDDEN:                 'FORBIDDEN',
  INSUFFICIENT_ROLE:         'INSUFFICIENT_ROLE',

  // Métier
  STOCK_INSUFFICIENT:        'STOCK_INSUFFICIENT',
  PROMO_EXPIRED:             'PROMO_EXPIRED',
  PROMO_MAX_UTILISATIONS:    'PROMO_MAX_UTILISATIONS',
  COMMANDE_NON_MODIFIABLE:   'COMMANDE_NON_MODIFIABLE',
  PAIEMENT_ECHOUE:           'PAIEMENT_ECHOUE',
  LIVRAISON_IMPOSSIBLE:      'LIVRAISON_IMPOSSIBLE',
  COMPTE_BLOQUE:             'COMPTE_BLOQUE',

  // Système
  INTERNAL_ERROR:            'INTERNAL_ERROR',
  DATABASE_ERROR:            'DATABASE_ERROR',
  SERVICE_UNAVAILABLE:       'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED:       'RATE_LIMIT_EXCEEDED',
  UPLOAD_ERROR:              'UPLOAD_ERROR',
  FILE_TOO_LARGE:            'FILE_TOO_LARGE',
  FILE_TYPE_INVALID:         'FILE_TYPE_INVALID',
};