// src/utils/constants/roles.js
// Définition des rôles et de la hiérarchie

const { COMPTE_ROLE } = require('./enums');

// Rôles liés à la plateforme (niveau admin global)
const ROLES_PLATEFORME = [
  COMPTE_ROLE.ADMINISTRATEUR_PLATEFORME,
  COMPTE_ROLE.STAFF_PLATEFORME,
  COMPTE_ROLE.BLOGUEUR_PLATEFORME,
];

// Rôles liés aux compagnies de transport
const ROLES_COMPAGNIE = [
  COMPTE_ROLE.ADMINISTRATEUR_COMPAGNIE,
  COMPTE_ROLE.STAFF_COMPAGNIE,
  COMPTE_ROLE.BLOGUEUR_COMPAGNIE,
  COMPTE_ROLE.ADMINISTRATEUR_EMBRANCHEMENT_COMPAGNIE,
  COMPTE_ROLE.STAFF_EMBRANCHEMENT_COMPAGNIE,
  COMPTE_ROLE.BLOGUEUR_EMBRANCHEMENT_COMPAGNIE,
];

// Rôles liés aux restaurants
const ROLES_RESTAURANT = [
  COMPTE_ROLE.ADMINISTRATEUR_RESTAURANT_FAST_FOOD,
  COMPTE_ROLE.STAFF_RESTAURANT_FAST_FOOD,
  COMPTE_ROLE.BLOGUEUR_RESTAURANT_FAST_FOOD,
];

// Utilisateurs finals
const ROLES_UTILISATEURS = [
  COMPTE_ROLE.UTILISATEUR_PRIVE_SIMPLE,
  COMPTE_ROLE.UTILISATEUR_VENDEUR,
];

// Tous les rôles administrateurs (toutes entités confondues)
const ROLES_ADMIN_TOUS = [
  COMPTE_ROLE.ADMINISTRATEUR_PLATEFORME,
  COMPTE_ROLE.ADMINISTRATEUR_COMPAGNIE,
  COMPTE_ROLE.ADMINISTRATEUR_EMBRANCHEMENT_COMPAGNIE,
  COMPTE_ROLE.ADMINISTRATEUR_RESTAURANT_FAST_FOOD,
];

// Tous les rôles staff
const ROLES_STAFF_TOUS = [
  ...ROLES_ADMIN_TOUS,
  COMPTE_ROLE.STAFF_PLATEFORME,
  COMPTE_ROLE.STAFF_COMPAGNIE,
  COMPTE_ROLE.STAFF_EMBRANCHEMENT_COMPAGNIE,
  COMPTE_ROLE.STAFF_RESTAURANT_FAST_FOOD,
];

// Tous les rôles blogueurs
const ROLES_BLOGUEURS_TOUS = [
  COMPTE_ROLE.BLOGUEUR_PLATEFORME,
  COMPTE_ROLE.BLOGUEUR_COMPAGNIE,
  COMPTE_ROLE.BLOGUEUR_EMBRANCHEMENT_COMPAGNIE,
  COMPTE_ROLE.BLOGUEUR_RESTAURANT_FAST_FOOD,
];

// Tous les rôles capables d'écrire des articles
const ROLES_REDACTEURS = [
  ...ROLES_ADMIN_TOUS,
  ...ROLES_STAFF_TOUS,
  ...ROLES_BLOGUEURS_TOUS,
];

module.exports = {
  ROLES_PLATEFORME,
  ROLES_COMPAGNIE,
  ROLES_RESTAURANT,
  ROLES_UTILISATEURS,
  ROLES_ADMIN_TOUS,
  ROLES_STAFF_TOUS,
  ROLES_BLOGUEURS_TOUS,
  ROLES_REDACTEURS,
};